### ISSUE TITLE
Create user 

### ISSUE THREAD

**Issue by msouidi309** [catogonzalez/universal-chat-widget#2]
Hi, thanks for this work, it's awesome ! I have a question , i want to have a form before having the chat widget where user can enter his username (and the password will be automatically generated) and then send data to my rocket chat backend to create this user. And finally display your vue.js widget.

i don't know if it's clear enough ..

**Comment by datanatas** [comment]
Hello msouidi309,

Sorry for such late reply. I don't know if you still need help but from your question I see you need some guidance with the form and user creation in Rocket Chat: I can't help you on those general issues. I suggest you narrow down the problem and ask in https://stackoverflow.com/.

**Comment by msouidi309** [comment]
Hi, thank you for the reply, i done it !
