### ISSUE TITLE
Example config for RocketChat adpater

### ISSUE THREAD

**Issue by sGaster** [catogonzalez/universal-chat-widget#3]
Hello :).

here,
just because it took me hours to find out the correct config params for the rocket chat adapter I give you an example for it that you can provide on the <>Code page of git hub.

config= {
    "adapter": "RocketChat", // one of ActionCable or RocketChat (required)
    "element": "#chat-widget",// css selector of element to replace in DOM when the chat widget renders (required)
    "position": "bottom-right", // or embedded
    "showAvatars": true, 
    "allowUploads": true,
    "poweredByText": "121 Services", // yes, you can change this :)
	"poweredByHost": "http://localhost:3000", // and this!
    "adapterConfig": {
        "backendUrl": "http://localhost:3000",
        "deviceId": "c683b9da-c908-4407-97dd-91e6bf2552d1",
        "initData": {
            "username": "testbot",
            "password": "123",
            "data": {
                "roomId": "GENERAL"
            }
        },
        "mode":"private"
    }
}

hope this help others to set up faster the uwc with rocket chat :).

You should also describe (for the beginners like me) that we have to build the adapter by our own and include it by copying it into node_modules folder. This path was not clear for a beginner like me.

Anyway, thank you for creating this universal chat client and building the adapter :) :+1:

**Comment by datanatas** [comment]
Hi sGaster,

Thanks for putting this together, and forgive my slow-reply: I have been with very limited time to dedicate to this project.

I have added your snippet to the documentation of the RocketChat adapter: https://github.com/catogonzalez/chat-adapter-rocketchat#configuration

Thanks again!
